Id: Datalust.Seq
Publisher: Datalust
Name: Seq
AppMoniker: seq
Version: 2020.1.4210
License: Copyright © 2013-2020 Datalust
LicenseUrl: https://datalust.co/doc/eula-current.pdf
MinOSVersion: 10.0.0.0
Description: Seq is the easiest way for development teams to capture, search and visualize structured log events.
Homepage: https://datalust.co/seq
Tags: logging
Commands: seq
InstallerType: msi
Scope: machine
Installers:
  - Arch: x64
    Url: https://datalust.co/download/begin?version=2020.1.4210
    Sha256: 11D2D71AEF973B97CABD3825C70E52E33982A4DA12D1700E715959C37C3FAD5C
    Switches:
      Silent: /quiet WIXUI_EXITDIALOGOPTIONALCHECKBOX=0
      SilentWithProgress: /passive WIXUI_EXITDIALOGOPTIONALCHECKBOX=0
      InstallLocation: INSTALLFOLDER=<INSTALLPATH>
# ManifestVersion: 0.1.0
